#!/usr/bin/env sh
if [ "x$npm_config_node_gyp" = "x" ]; then
  node "`dirname "$0"`/../../node_modules/node-gyp/bin/node-gyp.js" "$@"
else
  node "`dirname "$0"`/../../node_modules/node-gyp/bin/node-gyp.js" "$@"
  #"$npm_config_node_gyp" "$@"
fi
